osc_color=#000000
window_title_color=#FFFFFF
window_controls_color=#eabcb4
window_controls_close_hover=#ffb4ab
window_controls_minmax_hover=#ffb4a8
title_color=#FFFFFF
seekbarfg_color=#ffb4a8
seekbarbg_color=#5f3e39
seekbar_cache_color=#ffb4a8
volumebar_match_seek_color=no
time_color=#ffdad4
chapter_title_color=#eabcb4
chapter_marker_color=#afc6ff
chapter_marker_current_color=#ffb4a8
side_buttons_color=#eabcb4
middle_buttons_color=#ffdad4
playpause_color=#ffb4a8
held_element_color=#b08780
hover_effect_color=#FFFFFF
thumbnail_border_color=#ffb4a8
thumbnail_border_outline=#FFFFFF

show_on_pause=no
ontop_button=no
seek_handle_size=0
show_youtube_comments=yes
FORCE_fix_not_ontop=no
