osc_color=#000000
window_title_color=#FFFFFF
window_controls_color=#dcc0bd
window_controls_close_hover=#ffb4ab
window_controls_minmax_hover=#f4b9a0
title_color=#FFFFFF
seekbarfg_color=#ffb4ab
seekbarbg_color=#554240
seekbar_cache_color=#f4b9a0
volumebar_match_seek_color=no
time_color=#f9dcd9
chapter_title_color=#dcc0bd
chapter_marker_color=#fab982
chapter_marker_current_color=#ffb4ab
side_buttons_color=#dcc0bd
middle_buttons_color=#f9dcd9
playpause_color=#ffb4ab
held_element_color=#a38b88
hover_effect_color=#FFFFFF
thumbnail_border_color=#ffb4ab
thumbnail_border_outline=#FFFFFF

show_on_pause=no
show_youtube_comments=yes
seekbarbg_color=#999999
seek_range_alpha=75
